import requests

URX = 'https://engineering.tamu.edu/industrial/admission-and-aid/graduate-admissions/index.html'

URZ = 'https://citydev-portal.edinburgh.gov.uk/idoxpa-web/search.do?action=property&type=atoz'

urk = 'https://www.youtube.com/watch?v=T8nbNQpRwNo'

user = 'bengabp'
pwd =  'supersecretpasswordfortest'


proxy = f'http://bengabp:supersecretpasswordfortest@gate.dc.smartproxy.com:20000'

#x = requests.get(URZ,proxies={'http':proxy,'https':proxy})

print(len([1,2,3]))